# Generated by Django 3.1.2 on 2021-03-01 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Journal',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
