# Generated by Django 3.1.2 on 2021-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
